jenkins:
  image: nimkar/jenkins
  volumes:
    - ./sources/:/sources
    - ./jenkins/:/var/jenkins_home
  ports:
    - "18080:8080"
  dns:
    - 10.170.64.156
    - 10.170.64.158

sonarqube:
  image: sonarqube
  ports:
    - "19000:9000"
    - "5432:5432"
  environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar

database:
  image: postgres
  net: container:sonarqube
  environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar

gerrit:
  image: socialwifi/gerrit
  ports:
    - "18088:8080"
