jenkins:
  image: nimkar/jenkins
  volumes:
    - ./sources/:/sources
    - ./jenkins/:/var/jenkins_home
  ports:
    - "18080:8080"
  dns:
    - 10.170.64.156
    - 10.170.64.158

sonarqube:
  image: sonarqube
  ports:
    - "19000:9000"
    - "5432:5432"
  environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar

sonar_database:
  image: postgres
  net: container:sonarqube
  environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar

reviewboard:
  image: ikatson/reviewboard
  links:
    - "memcached:memcached"
    - "rb_database:pg"
  volumes:
    - ./sources/:/media
  ports:
    - "18000:8000"

memcached:
  image: sylvainlasnier/memcached
  ports:
    - "11211:11211"

rb_database:
  image: postgres
  environment:
    - POSTGRES_USER=reviewboard
    - POSTGRES_PASSWORD=reviewboard
